---
- name: recargar mysql_exporter
  ansible.builtin.systemd:
    daemon_reload: true
  listen: activar_servicio

- name: reiniciar mysql_exporter
  ansible.builtin.systemd:
    name: mysql_exporter
    state: restarted
    enabled: yes
  listen: activar_servicio

