---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Copia configuracion para mysql_exporter
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: files/mysqld_exporter.cnf.j2, dest: /etc/.mysqld_exporter.cnf }
    - { src: files/mysql_exporter.service, dest: /etc/systemd/system/mysql_exporter.service }
    - { src: files/sql_exporter.sql.j2, dest: /tmp/sql_exporter.sql }
  
- name: Agrega usuario "{{ mysql_exporter_user }}"
  mysql_db:
    state: import
    name: exporter_db
    target: /tmp/sql_exporter.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"  

- name: Descarga + descomprime mysql_exporter
  ansible.builtin.unarchive:
    src: "{{ mysql_exporter_url }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    extra_opts: --strip-components=1
    mode: 0755
    remote_src: true
  notify: activar_servicio