version: '3'
networks:
  db_net:
    name: db_net
    driver: bridge

services:
  db:
    image: mysql
    container_name: mysql_dumper
    networks:
      - db_net
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: mysql_data
    driver: local
